from imutils.object_detection import non_max_suppression
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import argparse
import imutils
import pickle
import cv2
import os

# construct the argument parser and parse the arguments
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", required=True,
	help="path to input image")
args = vars(ap.parse_args())

cwd = os.getcwd()
MODEL_PATH = os.path.join(cwd,"component_classifier.h5") 
ENCODER_PATH = os.path.join(cwd,"label_encoder.pickle") 
# load the our fine-tuned model and label binarizer from disk
print("[INFO] loading model and label binarizer...")

model = load_model(MODEL_PATH)
lb = pickle.loads(open(ENCODER_PATH, "rb").read())

# load the input image from disk
image = cv2.imread(args["image"])

# run selective search on the image to generate bounding box proposal
# regions
print("[INFO] running selective search...")
ss = cv2.ximgproc.segmentation.createSelectiveSearchSegmentation()
ss.setBaseImage(image)
ss.switchToSelectiveSearchFast()
rects = ss.process()

# initialize the list of region proposals that we'll be classifying
# along with their associated bounding boxes
proposals = []
boxes = []

# loop over the region proposal bounding box coordinates generated by
# running selective search
for (x, y, w, h) in rects:
	# extract the region from the input image, convert it from BGR to
	# RGB channel ordering, and then resize it to the required input
	# dimensions of our trained CNN
	roi = image[y:y + h, x:x + w]
	roi = cv2.cvtColor(roi, cv2.COLOR_BGR2RGB)
	roi = cv2.resize(roi, (240,240),interpolation=cv2.INTER_CUBIC)

	# further preprocess the ROI
	roi = img_to_array(roi)

	# update our proposals and bounding boxes lists
	proposals.append(roi)
	boxes.append((x, y, x + w, y + h))
# convert the proposals and bounding boxes into NumPy arrays
proposals = np.array(proposals, dtype="float32")
boxes = np.array(boxes, dtype="int32")
print("[INFO] proposal shape: {}".format(proposals.shape))

# classify each of the proposal ROIs using fine-tuned model
print("[INFO] classifying proposals...")
chunk_size = 256
nb_chunks = len(proposals)//chunk_size +1
print(nb_chunks, " chunks in total")
proba = []
for i in range(0,nb_chunks-1):
    print("chunk nb :" ,i)
    start = i*chunk_size
    proba.extend(model.predict(proposals[start:start+chunk_size]))
print("chunk nb :" ,nb_chunks-1)
proba.extend(model.predict(proposals[(nb_chunks-1)*chunk_size:]))
print("[INFO] applying NMS...")
objs =[]
for i,p in enumerate(proba):
    idx = np.argmax(p)
    conf = p[idx]
    if(conf >0.90):
        label = lb[idx]
        objs.append((label,conf,boxes[i]))

print("high preds",len(objs))
objs= [o for o in objs if not(o[0]=="not_component")]
print("pre final objects",len(objs))


clone = image.copy()

for label in lb.values():
    boxes = np.array([o[2] for o in objs if o[0]==label])
    proba = np.array([o[1] for o in objs if o[0]==label])
    boxIdxs = non_max_suppression(boxes, proba)
    print(label," : " , len(boxIdxs))
    # loop over the bounding box indexes
    for b in boxIdxs:
        (startX, startY, endX, endY) = b
        cv2.rectangle(clone, (int(startX), int(startY)), (int(endX), int(endY)),(0, 0, 255), 1)
        y = startY - 2 if startY - 2 > 2 else startY + 2
        text= label 
        cv2.putText(clone, text, (startX, y), cv2.FONT_HERSHEY_SIMPLEX, 0.15, (0, 0, 255), 1)

# show the output image *after* running NMS
cv2.imshow("After NMS", clone)
cv2.waitKey(0)
